CREATE TABLE area_codes (
    code INT NOT NULL,
    area VARCHAR(50) NOT NULL
)
INSERT INTO area_codes (code, area) VALUES
    (08,"Near North Side"),
    (32,"Loop"),
    (33,"Near South Side"),
    (05,"North Center"),
    (06,"Lake View"),
    (07,"Lincoln Park"),
    (21,"Avondale"),
    (22,"Logan Square"),
    (01,"Rogers Park"),
    (02,"West Ridge"),
    (03,"Uptown"),
    (04,"Lincoln Square"),
    (09,"Edison Park"),
    (10,"Norwood Park"),
    (11,"Jefferson Park"),
    (12,"Forest Glen"),
    (13,"North Park"),
    (14,"Albany Park"),
    (76,"O'Hare"),
    (77,"Edgewater"),
    (15,"Portage Park"),
    (16,"Irving Park"),
    (17,"Dunning"),
    (18,"Montclare"),
    (19,"Belmont Cragin"),
    (20,"Hermosa"),
    (23,"Humboldt Park"),
    (24,"West Town"),
    (25,"Austin"),
    (26,"West Garfield Park"),
    (27,"East Garfield Park"),
    (28,"Near West Side"),
    (29,"North Lawndale"),
    (30,"South Lawndale"),
    (31,"Lower West Side"),
    (34,"Armour Square"),
    (35,"Douglas"),
    (36,"Oakland"),
    (37,"Fuller Park"),
    (38,"Grand Boulevard"),
    (39,"Kenwood"),
    (40,"Washington Park"),
    (41,"Hyde Park"),
    (42,"Woodlawn"),
    (43,"South Shore"),
    (60,"Bridgeport"),
    (69,"Greater Grand Crossing"),
    (56,"Garfield Ridge"),
    (57,"Archer Heights"),
    (58,"Brighton Park"),
    (59,"McKinley Park"),
    (61,"New City"),
    (62,"West Elsdon"),
    (63,"Gage Park"),
    (64,"Clearing"),
    (65,"West Lawn"),
    (66,"Chicago Lawn"),
    (67,"West Englewood"),
    (68,"Englewood"),
    (44,"Chatham"),
    (45,"Avalon Park"),
    (46,"South Chicago"),
    (47,"Burnside"),
    (48,"Calumet Heights"),
    (49,"Roseland"),
    (50,"Pullman"),
    (51,"South Deering"),
    (52,"East Side"),
    (53,"West Pullman"),
    (54,"Riverdale"),
    (55,"Hegewisch"),
    (70,"Ashburn"),
    (71,"Auburn Gresham"),
    (72,"Beverly"),
    (73,"Washington Heights"),
    (74,"Mount Greenwood"),
    (75,"Morgan Park");
